#+TITLE: Configuration and analysis for "The equilibrium climate response to sulfur dioxide and carbonaceous aerosol emissions from East and Southeast Asia"
#+AUTHOR: Benjamin S. Grandey
#+OPTIONS: ^:nil

** Introduction
This repository contains details of the experimental design, model configuration, data management, and [[https://github.com/grandey/p17d-sulphur-eas-eqm/tree/master/analysis_draft2018a][analysis procedure and scripts]] for the manuscript titled "The equilibrium climate response to sulfur dioxide and carbonaceous aerosol emissions from East and Southeast Asia" by B. S. Grandey, L. K. Yeo, H.-H. Lee, and C. Wang (in preparation).

** Contents
1. [[https://github.com/grandey/p17d-sulphur-eas-eqm/blob/master/experimental_design.org][experimental_design.org]] provides an introduction to the *experimental design*.
2. [[https://github.com/grandey/p17d-sulphur-eas-eqm/tree/master/input_data_p17d][input_data_p17d/]] contains information and scripts relating to the *input data*.
3. [[https://github.com/grandey/p17d-sulphur-eas-eqm/tree/master/user_nl_cam][user_nl_cam/]] contains the =user_nl_cam= namelist files for the simulations.
4. [[https://github.com/grandey/p17d-sulphur-eas-eqm/tree/master/config_simulations][config_simulations/]] contains information and scripts for *creating, building, and submitting* the simulations. The scripts have been generated using the two =.org= files.
5. [[https://github.com/grandey/p17d-sulphur-eas-eqm/tree/master/analysis_draft2018a][analysis_draft2018a/]] contains scripts used for the *final analysis* of the simulation output data, including generation of the *figures* included in the manuscript.

** Scenarios
The scenarios described in this repository are named differently in the manuscript:
1. =year-2000= corresponds to *Ref*;
2. =eas0= is not analysed in the manuscript;
3. =eas0b= corresponds to *Exp1*;
4. =eas0c= corresponds to *Exp2*.

** Model input and output data
The model input data and the subset of the model output data analysed have been uploaded to Figshare: https://doi.org/10.6084/m9.figshare.6072887.

** Author
Benjamin S. Grandey, 2017-2018, in collaboration with Yeo Lik Khian, Lee Hsiang-He, and Chien Wang.

** Acknowledgements
This research is supported by the National Research Foundation of Singapore under its Campus for Research Excellence and Technological Enterprise programme.  The Center for Environmental Sensing and Modeling is an interdisciplinary research group of the Singapore-MIT Alliance for Research and Technology.  This research is also supported by the U.S. National Science Foundation (AGS-1339264) and the U.S. Department of Energy, Office of Science (DE-FG02-94ER61937).  The CESM project is supported by the National Science Foundation and the Office of Science (BER) of the U.S. Department of Energy.  We acknowledge high-performance computing support from Cheyenne ([[http://dx.doi.org/10.5065/D6RX99HX][doi:10.5065/D6RX99HX]]) provided by NCAR’s Computational and Information Systems Laboratory, sponsored by the National Science Foundation.

** Primary referance
B. S. Grandey, L. K. Yeo, H.-H. Lee, and C. Wang (in preparation), "The equilibrium climate response to sulfur dioxide and carbonaceous aerosol emissions from East and Southeast Asia".

