#+TITLE: Configure coupled atmosphere-ocean (B) simulations
#+AUTHOR: Benjamin S. Grandey
#+OPTIONS: ^:nil

** General notes

*** Experimental design
For an overview of the experimental design, please see [[https://github.com/grandey/p17d-sulphur-eas-eqm/blob/master/README.org][README.org]].

*** CESM version
The simulations use CESM 1.2.2.1 (CESM 1.2.2 configured for Cheyenne), found in =~/models/cesm1_2_2_1= on Cheyenne.

*** Component set
The coupled atmosphere-ocean (B) simulations will be based on the =B_2000_CAM5_CN= (=BC5CN=) [[http://www.cesm.ucar.edu/models/cesm1.2/cesm/doc/modelnl/compsets.html][compset]].

*** Processor layout
The simulations will be configured with a layout of =NTASKS=720= for all model components apart from the ocean. The 3D ocean will run concurrently with =NTASKS_OCN=128= and =ROOTPE_OCN=720=.  This layout is contained in =~/models/cesm1_2_2_1/scripts/pes/a720o128n24.xml= on Cheyenne. In total, 848 processors will be used, spread across 24 nodes. The 4 nodes being used for the ocean model will have a number of idle processors due to contraints with the ocean processor layout.

*** =user_nl_cam= files
The =user_nl_cam= files will be pulled from GitHub using =wget=. In addition to specifying the emissions, the =user_nl_cam= files also specify that data for dynamical downscaling should be produced:

#+BEGIN_SRC
fincl2 = 'PHIS:I','PS:I','PSL:I','Q:I','QREFHT:I','RHREFHT:I','SST:I','T:I','TREFHT:I','TS:I','U:I','V:I','Z3:I'

nhtfrq = 0, -6

mfilt = 1, 1
#+END_SRC

*** =user_nl_clm= file
The =user_nl_clm= file () will be pulled from GitHub using =wget=. This file specifies that 6 hour instantaneous soil temperature and water should be output, for use by WRF:

#+BEGIN_SRC
hist_fincl2 = 'TSOI_10CM:I', 'SOILWATER_10CM:I'

hist_nhtfrq = 0, -6

hist_mfilt = 1, 1
#+END_SRC

*** Symbolic link to run directory
To facilitate ease of access to the run directory, I like to create a symbolic link (=ln -s /glade/scratch/bgrandey/$CASENAME/run/ scratch_run=).

*** Submission to the =economy= queue
By default, my =.run= files are configured for submission to the =regular= queue. In order to submit to the =economy= queue, the =.run= file can be modified using =sed -i 's/regular/economy/g' $CASENAME.run=.

** Creation, configuration, and submission of coupled atmosphere-ocean (B) simulations

The source code blocks below are tangled using =C-c C-v t= in order to create bash scripts named =create_<CASENAME>.sh=.

*** DONE =p17d_b_2000=
CLOSED: [2017-08-15 Tue 14:29]

#+BEGIN_SRC :tangle yes :tangle create_p17d_b_2000.sh :shebang #!/bin/bash
CASENAME=p17d_b_2000

cd ~/models/cesm1_2_2_1/scripts/
./create_newcase -case ~/cesm1_2_2_1_cases/$CASENAME -res f19_g16 -compset BC5CN -mach cheyenne -pes_file pes/a720o128n24.xml

cd ~/cesm1_2_2_1_cases/$CASENAME
./cesm_setup
wget https://raw.githubusercontent.com/grandey/p17d-sulphur-eas-eqm/master/user_nl_cam/user_nl_cam_$CASENAME
mv user_nl_cam_$CASENAME user_nl_cam
wget https://raw.githubusercontent.com/grandey/p17d-sulphur-eas-eqm/master/user_nl_cam/user_nl_clm_p17d_b
mv user_nl_clm_p17d_b user_nl_clm
./$CASENAME.build
ln -s /glade/scratch/bgrandey/$CASENAME/run/ scratch_run
./xmlchange STOP_OPTION=nyears
./xmlchange STOP_N=10
./xmlchange RESUBMIT=9
sed -i 's/regular/economy/g' $CASENAME.run
./$CASENAME.submit
#+END_SRC

Notes:
- Case created, configured, built, and submitted on 2017-08-15.

*** DONE =p17d_b_eas0=
CLOSED: [2017-08-15 Tue 14:43]

#+BEGIN_SRC :tangle yes :tangle create_p17d_b_eas0.sh :shebang #!/bin/bash
CASENAME=p17d_b_eas0

cd ~/models/cesm1_2_2_1/scripts/
./create_newcase -case ~/cesm1_2_2_1_cases/$CASENAME -res f19_g16 -compset BC5CN -mach cheyenne -pes_file pes/a720o128n24.xml

cd ~/cesm1_2_2_1_cases/$CASENAME
./cesm_setup
wget https://raw.githubusercontent.com/grandey/p17d-sulphur-eas-eqm/master/user_nl_cam/user_nl_cam_$CASENAME
mv user_nl_cam_$CASENAME user_nl_cam
wget https://raw.githubusercontent.com/grandey/p17d-sulphur-eas-eqm/master/user_nl_cam/user_nl_clm_p17d_b
mv user_nl_clm_p17d_b user_nl_clm
./$CASENAME.build
ln -s /glade/scratch/bgrandey/$CASENAME/run/ scratch_run
./xmlchange STOP_OPTION=nyears
./xmlchange STOP_N=10
./xmlchange RESUBMIT=9
sed -i 's/regular/economy/g' $CASENAME.run
./$CASENAME.submit
#+END_SRC

Notes:

Notes:
- Similar to =p17d_b_2000=, but with a different CASENAME (which determines the =user_nl_cam= file to be used).
- Case created, configured, built, and submitted on 2017-08-15.

*** DONE =p17d_b_eas0b=
CLOSED: [2017-08-21 Mon 20:24]

#+BEGIN_SRC :tangle yes :tangle create_p17d_b_eas0b.sh :shebang #!/bin/bash
CASENAME=p17d_b_eas0b

cd ~/models/cesm1_2_2_1/scripts/
./create_newcase -case ~/cesm1_2_2_1_cases/$CASENAME -res f19_g16 -compset BC5CN -mach cheyenne -pes_file pes/a720o128n24.xml

cd ~/cesm1_2_2_1_cases/$CASENAME
./cesm_setup
wget https://raw.githubusercontent.com/grandey/p17d-sulphur-eas-eqm/master/user_nl_cam/user_nl_cam_$CASENAME
mv user_nl_cam_$CASENAME user_nl_cam
wget https://raw.githubusercontent.com/grandey/p17d-sulphur-eas-eqm/master/user_nl_cam/user_nl_clm_p17d_b
mv user_nl_clm_p17d_b user_nl_clm
./$CASENAME.build
ln -s /glade/scratch/bgrandey/$CASENAME/run/ scratch_run
./xmlchange STOP_OPTION=nyears
./xmlchange STOP_N=10
./xmlchange RESUBMIT=9
sed -i 's/regular/economy/g' $CASENAME.run
./$CASENAME.submit
#+END_SRC

Notes:
- Similar to simulations above, but with a different CASENAME (which determines the =user_nl_cam= file to be used).
- Case created, configured, built, and submitted on 2017-08-21.

*** DONE =p17d_b_eas0c=
CLOSED: [2017-08-23 Wed 15:40]

#+BEGIN_SRC :tangle yes :tangle create_p17d_b_eas0c.sh :shebang #!/bin/bash
CASENAME=p17d_b_eas0c

cd ~/models/cesm1_2_2_1/scripts/
./create_newcase -case ~/cesm1_2_2_1_cases/$CASENAME -res f19_g16 -compset BC5CN -mach cheyenne -pes_file pes/a720o128n24.xml

cd ~/cesm1_2_2_1_cases/$CASENAME
./cesm_setup
wget https://raw.githubusercontent.com/grandey/p17d-sulphur-eas-eqm/master/user_nl_cam/user_nl_cam_$CASENAME
mv user_nl_cam_$CASENAME user_nl_cam
wget https://raw.githubusercontent.com/grandey/p17d-sulphur-eas-eqm/master/user_nl_cam/user_nl_clm_p17d_b
mv user_nl_clm_p17d_b user_nl_clm
./$CASENAME.build
ln -s /glade/scratch/bgrandey/$CASENAME/run/ scratch_run
./xmlchange STOP_OPTION=nyears
./xmlchange STOP_N=10
./xmlchange RESUBMIT=9
sed -i 's/regular/economy/g' $CASENAME.run
./$CASENAME.submit
#+END_SRC

Notes:
- Similar to simulations above, but with a different CASENAME (which determines the =user_nl_cam= file to be used).
- Case created, configured, built, and submitted on 2017-08-23.

